---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - ls
  - mv ansible-role-selenium_hub wouterdt.selenium_hub
  - cd wouterdt.selenium_hub

script:
  # Run tests.
  - molecule test
  
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
